### ISSUE TITLE
Loading ROMS

### ISSUE THREAD

**Issue by orff** [lesbird/MAME4apple-037b5#1]
Do I need a /roms/ folder ?  Ive tried all kinds of things with 1943 since its top of the list and it doesn't seems to find the files.

**Comment by pinni74** [comment]
At least yours builds my friend. I'm curious to see where roms go myself actually. Let's wait and see from the masters themselves 😆

**Comment by lesbird** [comment]
I updated the wiki to reflect where roms and samples should go. Make a folder called roms and put your roms in there and then drag that to the file sharing folder in iTunes or if you have the complete MAME4all set just drag the roms, artwork and samples folder to file sharing.

**Comment by pinni74** [comment]
How does that work for Apple TV?

Paul Pianalto

**Comment by lesbird** [comment]
Paul, it does not work with AppleTV at this time. I'm trying to figure out the best way to do this. If anyone has any suggestions I'm listening.

**Comment by pinni74** [comment]
Like Provenience and the web server function that allows uploading to the roms folder on the Apple TV perhaps?

Regards,

Paul Pianalto
Mobile: +61 432 255 482

On 19 Oct. 2016, at 12:15 pm, Les Bird notifications@github.com wrote:

Paul, it does not work with AppleTV at this time. I'm trying to figure out the best way to do this. If anyone has any suggestions I'm listening.

**Comment by lesbird** [comment]
Paul, that's interesting but not exactly what I was thinking of. What I'd like to do is use OnDemandResources and load the roms from iCloud Drive. Trying to figure out how to get this to work.

**Comment by pinni74** [comment]
That sounds pretty nifty but remember a lot of people have free iCloud accounts and after iOS device backups you limit how much of the 5Gb can be utilised for roms. Would it be used as an intermediary to upload permanently to the device or just a storage point mame accesses roms from? Personally I'd like to dump the entire rom pack and set and forget if you will. Now I have a paid 1Tb plan so I'm good with the iCloud route but be mindful you apply some constraints to those who don't have that flexibility. You could use SMB or AFP shares but again it's not a standalone platform. Some considerations for you sir! :-)

Regards,

Paul Pianalto
Mobile: +61 432 255 482

On 19 Oct. 2016, at 10:40 pm, Les Bird notifications@github.com wrote:

Paul, that's interesting but not exactly what I was thinking of. What I'd like to do is use OnDemandResources and load the roms from iCloud Drive. Trying to figure out how to get this to work.

**Comment by lesbird** [comment]
Apple TV support has been added. I've tested it on Apple TV (tvOS) using a Steelseries Nimbus MFi controller. Roms are copied to a roms.bundle file that has been added to the project. I've included in the roms.bundle the "samples" and "artwork" from the MAME4all rom set but no roms are included, you need to track those down yourself. Even though the app bundle is over 2GB in size with all the roms if you install from Xcode it will work just fine. At least that's what I'm seeing in my tests. See the wiki for details.

**Comment by orff** [comment]
Thanks !  Working great now, esp with the filtering.

**Comment by rockdirector** [comment]
Les, would it be possible to allow fast scrolling through the ROM list on an AppleTV? Either by scrolling a page at a time using the left joystick, or by holding down the keypad to speed up? I have a fairly robust bundle of games and it takes a long time to get past the first few letters. Thanks again for your awesome work.
