### ISSUE TITLE
Developer Account Error

### ISSUE THREAD

**Issue by Tunnelrat319** [lesbird/MAME4apple-037b5#11]
I have been trying to sideload MAME4apple-037b5 on to my Apple TV 4th gen for a couple of days and I keep running into the same errors. The install keeps stating that I need to be part of a certain development team and something about push notifications. I'm not quite sure how to get around this and I have not had these issues sideloading other apps (Provenance and Browser).  Is there an instructions guide for your version of MAME for tvOS or can you offer up any tweaks/workarounds I can perform on my end?  I am new to sideloading and don't have any development background.  I'm just super excited to add this project to my Apple TV.  Thanks in advance.

**Comment by lesbird** [comment]
Let me take a look. I think that might have something to do about some of the settings in the project. I will disable push notifications and update the project.

update: project has been updated let me know if that fixes the problem.

**Comment by Tunnelrat319** [comment]
Great news!  Your fix got me past all errors. Build succeeded and Mame app appears on my ATV.  However, when the app loads, I'm taken to a black screen with a list of my roms and I can't seem to scroll through or select any games.  I have tried using the ATV 4G remote, the ATV old remote and an 8Bitdo controller.  I also ran this as an Apple TV 1080p simulator and got the same results.

Let me know if you need any more info.

**Comment by lesbird** [comment]
The Apple TV build requires a MFi controller. I use the SteelSeries Nimbus controller which can be ordered from the Apple Store or you can pick one up at Best Buy. The Apple TV remotes will not work. See the Wiki page for controller button assignments. [MAME4apple Wiki](https://github.com/lesbird/MAME4apple-037b5/wiki/MAME4apple-Wiki-Home)

**Comment by Tunnelrat319** [comment]
Gotcha.  I thought there would be limited functionality with the remote but that makes sense.  I will have the SS Nimbus later today or tomorrow and will confirm that all is working great.  Thanks for putting all of this together and taking the time to help troubleshoot.

Update:  Got the Nimbus and it is working great! Thanks for the button guide and all the work you put into this.  A bunch of great games are now at my fingertips.
