### ISSUE TITLE
Some ROMS not loading

### ISSUE THREAD

**Issue by Tunnelrat319** [lesbird/MAME4apple-037b5#12]
I have been able to play a bunch of games, but there are some that don't seem to be working; just going to a black screen (despite using the Mame4all bundle list).  Issue includes all versions of the Mortal Kombat series, the NBA Jam series, the King of Fighters series and the Street Fighter series. There have been more, but these seem to show issues within the groups.

Also, I have tried rebuilding the rom sets with CLRMAMEPro using the MAME 0.37b5 dat file, both as Merged Sets and Split Sets, but that didn't fix the problem. I also tried including the latest set of bios in the roms folder (is that the correct location?) and that did not seem to have an effect.

Please, let me know if there is something I am missing or if these games are not meant to work.  There's a ton of other games that work perfectly, but it would great if these ran, too.  Let me know if you need any more info.  Thanks again for all your work!

**Comment by lesbird** [comment]
Hi, I don't think those games work with the 0.37b5 core. I will double check.

UPDATE: those games are indeed supposed to work. I will look into it.

**Comment by lesbird** [comment]
Fixed the older Mortal Kombat games but some of the newer ones, Mortal Kombat 3, do not work. NBA Jam does not crash now but it still does not work properly. Most of the Street Fighter games should be working now but some seem to have screen centering problems. There's a weird issue in some games where screen dimensions are reported to osd_create_display() that are different than the actual bitmap dimensions. I will need to figure out a consistent way to get this information so it computes the proper scale and offsets. King Of Fighters all seem to work now. A lot of broken games should be working now.
