### ISSUE TITLE
A lot of errors when I select archive 

### ISSUE THREAD

**Issue by appletv4** [lesbird/MAME4apple-037b5#13]
I'm getting a lot of errors when I select archive and is not compiling correctly even though I get build successful at the end 
Over 20 errors 

I use the archive option to get the .ipa file to upload to ipwnstore so I can avoid the 7 day limit 

When I upload the .ipa  to ipwnstore it doesn't work , doesn't upload 

Uploading provenance works fine and I don't get any errors when archiving provenance 

Can you fix the errors you get when you archive the project

**Comment by appletv4** [comment]
this is on the apple tv

the errors over 800 reads like this

"implicit conversion loses integer precision 'unsigned long to int'

**Comment by lesbird** [comment]
Hi, those are warnings, not errors. They should not prevent you from building an archive. I was able to successfully build an archive myself as a test so it should be working ok. If you can find the actual error message then I might be able to help but the "implicit conversion" warnings should not stop you from creating an archive. Errors will show up with a red icon.
