### ISSUE TITLE
Can't see any rom.

### ISSUE THREAD

**Issue by sapidog** [lesbird/MAME4apple-037b5#16]
I already copy pacman.zip to rom folder , but still can't see any rom in app
my environment : Xcode 8.2 tvos10.1

**Comment by lesbird** [comment]
Hi, when you say you copy it to the rom folder which folder is that? It should be inside the roms.bundle file and within the bundle a folder called roms. The path should be roms.bundle/roms/pacman.zip. If it does not show up then it's very possible it is the wrong rom version. Make sure the rom is for MAME 0.37b5.

**Comment by sapidog** [comment]
Oh!, its working , Very Thx
