### ISSUE TITLE
Apple TV 4 black screen

### ISSUE THREAD

**Issue by vitalizm** [lesbird/MAME4apple-037b5#17]
Hi Les,
I've compiled and installed this on my Apple TV 4. I copied over a rom to the new roms folder and I see it displayed on the first screen when launching the app. However, nothing happens when I select it. Just a black screen. Also, in the wiki you mention to copy the "full rom set" where do you get this full rom set?
The version that shows on the screen is MAME4apple V1.2 and im using XCODE 8.2.
Other than loading my own rom to the ROM folder in roms.bundle, is there anything else required to play? Thanks!

**Comment by lesbird** [comment]
If you launch the game and see only a black screen that most likely means the game is not supported or the rom is not for MAME 0.37b5. Try locating a different rom for 0.37b5 and see if that works.

You can find the full MAME4all rom set by doing a google search for it. The size for the full set is approximately 2 GB.

**Comment by 237overlook** [comment]
Hi Les,

First of all ... thank you working on this - an truly worthy project.

I think I get a similar problem. I've built and installed along with the full rom set. I basically get a blackscreen with a list of the first dozen roms. At the bottom of the screen on the left is the number "2240" on the right it says "nodes:59" and gives a frame rate which changes.

However, I cannot interact with anything. Nothing is highlighted and nothing moves!

Kevin

**Comment by sapidog** [comment]
Hi Overlook 
Maybe you need a Game controller such as "SteelSeries' Nimbus" , I can control and playback through it.

**Comment by 237overlook** [comment]
Hi Sapidog,

Good point. Does it not work for you with the Apple remote? I do have a Nimbus and will try with that as soon as I get back home.

**Comment by sapidog** [comment]
HI Overlook
I can't use apple remote in MAMEAPPLE app too.

**Comment by 237overlook** [comment]
Thanks. I'll let you know how I get on!

**Comment by 237overlook** [comment]
It works! Thanks Sapidog.

**Comment by 237overlook** [comment]
One other comment though ... it is very difficult on my TV to see which rom is currently selected! I've worked out that it is the one roughly in the middle of the screen. I guess a nice front end (a la Provenance) is something for future development (hopefully :-)). Anyway, fantastic work all round!

**Comment by lesbird** [comment]
Adjusted the colors to make AppleTV selected game easier to see.

**Comment by 237overlook** [comment]
You're a star! :-)
