### ISSUE TITLE
Runs Better on iPhone 5s than iPhone 7

### ISSUE THREAD

**Issue by asplogic** [lesbird/MAME4apple-037b5#20]
The app performs much better on the older iPhone 5s than the iPhone 7.  It seems to be way more laggy on the iPhone 7.  Are there any files or functions that can be manually edited to optimize the frame rate?  If you can point me to those, I can give it a try.  Thanks.

**Comment by asplogic** [comment]
What I ended up doing was increase the frame rate buffer and that seem to do the trick for most games.

-(void)initFrameBuffer
{
    UINT32 bufferWidth = 10240;
    UINT32 bufferHeight = 10240;
...

**Comment by lesbird** [comment]
I'm actually surprised that increasing the frame buffer size made a difference. I'll give it a try.
