### ISSUE TITLE
No menu or games appearing after install

### ISSUE THREAD

**Issue by belltechdave** [lesbird/MAME4apple-037b5#23]
I installed the mame app onto my Apple TV 4 and after it finished running in Xcode then there was nothing but a black screen with some text at the bottom.  No menu, no games.  Any ideas why nothing appears, any help would be much appreciated.  Thank you in advance

**Comment by lesbird** [comment]
Hi not sure if you figured this out yet but you need to follow the directions on this page:
https://github.com/lesbird/MAME4apple-037b5/wiki/MAME4apple-Wiki-Home

Specifically you need to make sure you copy your roms (MAME4all rom set) into the roms.bundle file and then sync the entire app bundle (2+GB) to your AppleTV.
