### ISSUE TITLE
Coin Exit Start Options buttons not visible

### ISSUE THREAD

**Issue by yogi1967** [lesbird/MAME4apple-037b5#3]
I know it's work in progress... I cannot see these buttons. I have to press a few times top right/left to get games to start by guessing and moving where I am pressing.... Ditto for exit. However, did get first game running (1942) using touch controls.... Thanks

**Comment by lesbird** [comment]
Should be working much better now. I added visible representations of the buttons in the corners and changed the way taps are detected for them.
