### ISSUE TITLE
Explanation to the ergonomy / buttons

### ISSUE THREAD

**Issue by pafffff** [lesbird/MAME4apple-037b5#4]
Hello
I could compile and install MAME4apple on my iPhone 5S and it seems to work. I found out how to scroll through the list (not very intuitive, it seems I have to touch and move the buttons top left und down left), and after pressing everywhere on the screen, sometimes a game starts but I still haven't understood where the following buttons are:
- left/right/up/down
- fire 1, fire 2
- \+ coin
- start game
- menu for setup / configuration (if implemented).

Furthermore, are the buttons half off-screen "by design" (annexed screenshot)? 

Anyways, thanks for bringing MAME to IOS 10!
Patrick

![img_1752](https://cloud.githubusercontent.com/assets/23074705/19722272/36a6a786-9b76-11e6-8875-9929e66c7538.PNG)

**Comment by lesbird** [comment]
Hi, the touch controls are experimental. I highly recommend using a MFi controller to get the best experience. The buttons in the corners are (top left) add coin (top right) start game (bottom left) exit game back to front end. The onscreen joystick works by touch the left half of the screen. The joystick will anchor where you touch and you can move it left/right/up/down. When you lift your finger the joystick disappears. When playing you should rotate to landscape so the action buttons can space themselves better.

**Comment by pafffff** [comment]
Thank you for the explanation.
In the game selection screen:
-   it seems a double-click starts the selected game, right?
-   what's the use of the middle top button, it seems to change the game's order?
-   any menu with options?
-   any way to see only the installed games?

When in the game: 
-   what's the use of the top middle button ?

I have only tried "1941". It's almost impossible to control. I guess that having a "fix" joystick at the bottom end of the screen (and move the game to the top) would be easier. You have to use this game in portrait mode, as it was originally in the arcades, else the screen is too small.
Why not put the explanation of the keys on the wiki pages?
Anyways, great work!

**Comment by lesbird** [comment]
Double tap starts the game, yes that is correct. The middle button sorts the game list by manufacturer or alphabetical. So if you want to see all the Atari games grouped together you can sort by manufacturer. No options menu "yet". No way at this time to see only installed games. Most of these issues will get resolved as the project matures.

**Comment by pafffff** [comment]
OK, thanks. Looking forward to the next versions!
