### ISSUE TITLE
Compile for touch controls

### ISSUE THREAD

**Issue by iostriz** [lesbird/MAME4apple-037b5#6]
I wanted to compile MAME for iPhone with the touch controls. I have changed define from 0 to 1 in line 20 of the GameScene.m:

`
#define USE_TOUCH_CONTROLS 1
`

When I do that, compile fails with 'Use of undeclared identifier x...'

**Comment by lesbird** [comment]
I just updated the project for better touch controls this past weekend. Please get the latest. It should default to USE_TOUCH_CONTROLS 1 so you should not have to change that for iOS devices. The version number has been bumped up to 1.1.

**Comment by iostriz** [comment]
Great! It works now!
What should I press instead of typing "OK"?
Maybe updating a Wiki page?

**Comment by lesbird** [comment]
Just move the onscreen joystick left and right. Touch the left half of the screen to see the joystick.
